[terminal]
shell = { program = "/usr/bin/tmux", args = ["new-session", "-A", "-s", "main"] }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0

[bell]
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/bell.oga"] }

[hints]
enabled = [{ regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|nntp:|sftp:|ssh:|telnet:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+", hyperlinks = true, command = { program = "xdg-open", args = [] }, post_processing = true, mouse = { enabled = true, mods = "Shift" } }]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
